version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres:
